### ISSUE TITLE
renderBackend[B] fails compilation in Scala 3 when the backend takes implicit parameters

### ISSUE THREAD

**Issue by DanielMoss** [japgolly/scalajs-react#1052]
Hi. Thanks for the great library.

I'm experimenting with upgrading a project I've got to Scala 3, and had some code stop compiling unexpectedly. Here's what I'm playing around with:
```scala
import japgolly.scalajs.react.component.Scala.{BackendScope, Component}
import japgolly.scalajs.react.vdom.VdomNode
import japgolly.scalajs.react.{CtorType, ScalaComponent}

import scala.language.implicitConversions

object Test {
  /* Successfully compiles in both Scala 2.13 and Scala 3.0 */
  def buildV1[N : Numeric]: Component[N, N, Backend[N], CtorType.Props] =
    ScalaComponent
      .builder[N]
      .initialState(Numeric[N].zero)
      .backend(new Backend(_))
      .renderBackend
      .build

  /* Successfully compiles in Scala 2.13, but fails in Scala 3.0
   * [error] 30 |    ScalaComponent
   * [error] 31 |      .builder[N]
   * [error] 32 |      .initialState(Numeric[N].zero)
   * [error] 33 |      .renderBackend[Backend[N]]
   * [error]    |    ^
   * [error]    |    no implicit values were found that match type Numeric[N]
   * [error]    | This location contains code that was inlined from Test.scala:14
   * [error]    | This location contains code that was inlined from ComponentBuilder.scala:145
   */
  def buildV2[N : Numeric]: Component[N, N, Backend[N], CtorType.Props] =
    ScalaComponent
      .builder[N]
      .initialState(Numeric[N].zero)
      .renderBackend[Backend[N]]
      .build

  final class Backend[N : Numeric](scope: BackendScope[N, N]) {
    def render(props: N, state: N): VdomNode =
      ???
  }
```
I've included this code in a small project over [here](https://github.com/DanielMoss/scalajs-react-renderBackend-debugging), in case anyone wants to play about with it.

I imagine this is related to the macro changes that have happened, but I'm only just dipping my toes into Scala 3 so I'm not sure what exactly is going wrong at the second.

**Comment by japgolly** [comment]
Hi @DanielMoss, thanks for the debugging help! I've got some bad news for you.

1. I can't implement this because a feature I need still hasn't been added to Scala 3 non-experimentally (see [1](https://github.com/lampepfl/dotty/issues/12392), [2](https://github.com/lampepfl/dotty/pull/13166))
2. I [can make it work for simple substitutions](https://github.com/japgolly/microlibs-scala/pull/160) but I can't do higher-kinded substitutions due to [another missing piece of functionality in Scala 3](https://github.com/lampepfl/dotty/issues/14740)

Unfortunately you'll have to persist with your workaround for a while longer I'm afraid

**Comment by DanielMoss** [comment]
No problem at all @japgolly. Thanks very much for all the context - I wasn't even aware that type substitution was something we have to take care of ourselves when in macro land.

**Comment by japgolly** [comment]
No worries at all and I wish I couldn't come back to you with a better result. It's still early days for Scala 3 but we'll get there eventually 🙂
