### ISSUE TITLE
Type-inference + contravariance breaks TagMod conversion

### ISSUE THREAD

**Issue by bblfish** [japgolly/scalajs-react#125]
As [reported on gitter](https://gitter.im/japgolly/scalajs-react?at=555e16d627740b8f26daf0e1)

```scala
  <.div(fstyle.name, ^.title := nameOpt.getOrElse(""), ^.onClick ==> B.enterEdit) {
          nameOpt.getOrElse("")
      }
```

does not compile, even though `nameOpt` is defined as an `Option[String]`. One needs instead to write [See line 35 of NameInfo.scala](https://github.com/read-write-web/rww-scala-js/blob/7512d5ad8afc004474b18700b3f823e9b1cf5499/src/main/scala/rww/ui/foaf/NameInfo.scala#L35)

```scala
   <.div(fstyle.name, ^.title := nameOpt.getOrElse(""), ^.onClick ==> B.enterEdit) {
          nameOpt.getOrElse[String]("") //<- todo: does not compile without the [String]
      }
```

This looks like a compiler problem. But it could be due to something else?

**Comment by bblfish** [comment]
apparently one should not bother with `getOrElse("")` as that is done automatically. So this is perhaps a conversion problem?

**Comment by bblfish** [comment]
Still I wonder if I would not get the problem if I had `opt.getOrElse("other")`

**Comment by japgolly** [comment]
This is a Scala bug. Scala's type-inference does some really stupid things when type-variance is involved and in the case of `Option[A]#getOrElse`, if it were `getOrElse: A` instead of `getOrElse[B >: A]: B` this would work fine. But that's just how both Scala stdlib is & how the hacky type-inference works (or doesn't work).

In your case you can do:
```scala
<.div(fstyle.name, ^.title := nameOpt, ^.onClick ==> B.enterEdit, nameOpt)
```

If you wanted a default, you could do
```scala
val name = nameOpt getOrElse "?"
<.div(fstyle.name, ^.title := name, ^.onClick ==> B.enterEdit, name)
```

What else can we do? I considered very briefly an implicit class over Option with an invariant version of `getOrElse` but who'd use it or know to use it? It's such a snowflake scenario to workaround a Scala issue. I think calling `getOrElse` the line before creating tags, or just saying `getOrElse[String]` are workarounds enough.

**Comment by bblfish** [comment]
thanks. It's worth keeping this around for documentation. Could be a nice practical use case for improved inferencing.

**Comment by japgolly** [comment]
Documented in ad568a4f76f8e73129512cb3ffe69c1aad360651
