### ISSUE TITLE
Why is Scalatags' AttrValue private?

### ISSUE THREAD

**Issue by arturaz** [japgolly/scalajs-react#136]
It would be nice to write own instances of it, allowing custom types to be used as values directly.

**Comment by japgolly** [comment]
Scalatags is an implementation detail. I don't expose it directly because I want to be able to make significant changes to it without affecting users' code or worrying about maintaining backward-compatibility.

Is there not a way for you to create an implicit that after your own logic, comes through one of the existing `AttrValue` implicits?

**Comment by japgolly** [comment]
I don't understand how this compiles. Maybe this is a compile bug? `vdom.Scalatags` is private, `AttrValue` is a public trait within, I don't understand why the public implicits in the public `vdom.Implicits` class don't fail with *public blah exposing private blah*. It should.

**Comment by arturaz** [comment]
> Is there not a way for you to create an implicit that after your own logic, comes through one of the existing AttrValue implicits?

Not sure what you mean by that.

**Comment by japgolly** [comment]
I mean can you not have a conversion from your custom type to one of the supported types? I believe that will work without needing any knowledge of Scalatags' inner model.

**Comment by arturaz** [comment]
AFAIK double implicit conversions doesn't work.

E.g.: Foo -> String -> AttrValue[String].

Otherwise I was trying to avoid typing .value for my Foo instances
everywhere where AttrValue is needed.

**Comment by japgolly** [comment]
Cool. Well I'll just make `AttrValue` and `StyleValue` public then.
Closed via 5f6893a
