### ISSUE TITLE
React native support in Router

### ISSUE THREAD

**Issue by mkotsbak** [japgolly/scalajs-react#151]
I guess the router included with scalajs-react is not possible to use since it interacts with the URL bar and possibly the DOM.

I have no experience with iOS development, but I assume it would be nice to have something similar to structure the application. It would be extra nice if the API would be the same as for the web router.

I opened the issue here too: https://github.com/chandu0101/scalajs-react-native/issues/2

**Comment by japgolly** [comment]
Sorry but I don't really get the point of this issue. This library focuses on React.JS only. I don't know about, or use React Native. Do you have something more concrete because currently this issue is too vague to be actioned? If it's just for exploring ideas, that's cool but I think it should be done on the react native side as the number one focus of this lib is the best experience using Scala & React(.JS); better integration with other libs is nice-to-have but not a priority and not something I can afford to spend my (unfortunately yet consistently) limited time on. Best to come back with something concrete, get the idea approved then PR.

**Comment by mkotsbak** [comment]
I see. That is why I reported it in the other project too.
