### ISSUE TITLE
Support Relay and GraphQL

### ISSUE THREAD

**Issue by pasviegas** [japgolly/scalajs-react#167]
Hey, is there a plan to support relay/graphql any time soon?

It would be an awesome addition to the project. :)

Thanks

**Comment by japgolly** [comment]
Hey there!

Answer: No, sorry. I don't see myself ever having the time and interest to add such features. Even if someone kindly contributed such support I would have to decline due to the cost of eternal maintenance (which is already quite high, sadly). 

The best option would be for interested parties to create Relay/GraphQL/Flux/x functionality as addon modules. If that's not possible for some reason, I'm happy to make changes to this library so that the community can freely create such modules on top of scalajs-react without a problem.

I'll close this issue but feel free to discuss further if you like. Cheers.
