### ISSUE TITLE
Add BackendScope.{props,state}CB

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#169]
In backends:
In `render` fns you want everything now (e.g. `$.state: State`).
For all methods not *executed directly* in `render` fns, you want `CallbackTo`s (e.g. `$.state: CallbackTo[State]`). Especially when creating backend `val`s, accessing immediately is a bug, hard to detect but easy to create.

What a pain... Think about this more... (Also remember #87)

**Comment by elacin** [comment]
This too, would be wonderful. It has both been one of the few sources of bugs, and the cause of some mental dissonance in the sense that my mind still, after repeated failure, keeps thinking of props as immutable for a given component. Forcing this into the type system is big win.

On a partly related note, I experimented with only exporting `state`/`props` to `Backend` through containers like you're proposing, both to avoid this very problem, and to be able to make pseudo-vals that would cache the result of a computation based on props/state as long as those didn't change. https://gist.github.com/elacin/f43b3edf1b681c78cd61

**Comment by japgolly** [comment]
Yeah this is a frustrating one. Problem is I don't know if we actually can solve it via the type system. My current thoughts are: when the scope is used within a backend we have no way of knowing whether access is needed right now or in a callback. With dread I think static analysis & reachability is probably the only way. That's not going to happen. :(

I'd love to hear other ideas. This is a  genuine source of bugs, I'd love to be able to prevent them using the compiler.

As to your gist, there's already a feature that does what you're doing with your `ReactVal` type: it's [`Px`](https://github.com/japgolly/scalajs-react/blob/master/extra/PERF.md#px).
You can achieve the same functionality as the gist, by adding
```scala
  val props = Px.thunkA($.props)
  val state = Px.thunkA($.state)
  val both = Px.apply2(props, state)(Tuple2.apply)
```
to your backend.

**Comment by elacin** [comment]
Wow, i hadn't noticed `Px` - wonderful!

Anyways, for the issue here. It would make perfect semantic sense (in my mind, at least) if `BackendScope` always exposes only `CallbackTo[Props`|`State]`, while you are passed plain instances of `Props`/`State` when you specify a `render` method while building the component, so that you can in turn pass them as arguments to `render()` - whether it's inline or if it lives in the backend. 

Would it be possible to massage the integration with react so that would work?

**Comment by japgolly** [comment]
Ah, that's really cool idea! That might be the solution we need! At the minimum should be able to make that change to `BackendScope` without a problem. I'm not sure if it should also apply to the other `ComponentScope{U,M,xx}` types. Well actually *technically* it should always apply on all types (thinking of `Callback` as meaning "Impure") but I'm not sure if it would make the library annoying to use. Maybe some experimentation is needed.

**Comment by japgolly** [comment]
In lifecycle callbacks (`componentWillUnmount`, `shouldComponentUpdate`) this is bad as you're expected to call `.props|state` immediately without any problems.

So...
`BackendScope` - dangerous not to wrap in `CallbackTo`
lifecycle scopes - stupid to wrap in `CallbackTo`
`ScopeU` & `ScopeM` - ?

**Comment by elacin** [comment]
Hmm, I can see one point for and one against wrapping lifecycle callbacks in `CallbackTo`. 

Semantically, it doesn't make sense, because the passed functions are event handlers meant to operate on props/state at a given point in time.

The point for is that you often call methods on the backend, which necessarily would return a `CallbackTo`, and it might seem clumsy to call runNow() yourself.

I would say keep them as they are, unless you want to provide overloads.

**Comment by japgolly** [comment]
Yeah, I'm thinking a similar thing. Actually this issue is proving harder than I thought. I experimented with different cases yesterday (current backends, improved backends, components as scala classes, components as JS classes) and can't seem to find a good approach to where and how much to spread `Callback` (including not at all).

If I choose a rule (like purity or dom/react callback-targeted) and apply it consistently (including not using `Callback` at all), then it always ends up applied everywhere, i.e. every lifecycle callback (inc. `render`), every React call. It's crazy. There's a line here but I'm struggling to find it.

What I know...
* I know that `render` should return a `ReactElement`, not a `CallbackTo[ReactElement]`.
* I know that dom callbacks should be wrapped in `Callback`, safe from accidental transformation which side-effects, and comprehensible to the type system.
* I know I want all the `=> Unit` lifecycle callbacks (like `componentDidMount`) providing `Callback`, comprehensible to the type system, fencing off effects and allowing sane composition (like in mixins & client code).
* I know that every time I've accessed `.props` in a backend outside of a `render` fn or callback, it's been a bug (and so easy to forget that I've made it multiple times).

What I think...
* I think it will be a nice solution to have `BackendScope` wrap its props/state in `CallbackTo`, and have a `render` fn accept unwrapped props and state (@elacin your idea).
* I think it will be nice if I use a macro to have `ReactComponentB` discover the backend's `render` fn, figure out the needed arguments (any combination of P, S, PropsChildren) and supply it automatically.
* I think lifecycle scopes can just return props/state directly without a problem.
* I think if you're outside of a component and have a reference to it `ReactComponentM`, you should be able to get props/state directly without a problem. You'd probably be in an ajax callback or something. In which case, should `{set,mod}State` not also just complete directly and return dreaded `Unit`?
* I think I'm going to cry when I implement components as classes (at least if I follow the plain-JS style). There, you just get `this` and you call whatever directly, any time you feel like it. That would give no support from the compiler, and is so error-prone. I really don't want to waste my time chasing down runtime errors. How could I enforce React's loosely written rules using the compiler and `CallbackTo` in that situation?

Suggestions very welcome.

**Comment by elacin** [comment]
Loads of interesting questions here. I'll just try to help the process along by posting my thoughts at least. Would be great if more people would chime in - I suspect my view is somewhat narrow.

> What I know...

No problems here, and it itself a huge win for the library, I'd say.

> I think it will be a nice solution to have BackendScope wrap its props/state in CallbackTo, and have a render fn accept unwrapped props and state (@elacin your idea).

I have been experimenting a bit with a simple [backend wrapper](https://gist.github.com/elacin/0e6e4cce8132f6b8a315). So far:
* + signal through types that `Props`/`State` will change feels more correct and less bug prone
* + threading data through `render()` as parameters cleans things up. type signatures that means something. At this point i barely see why `render()` should live in a `Backend` and have any special access at all.
- - Access to `Props` is cumbersome and feels a bit wrong. I would expect/prefer `Px`-like semantics  (cache) rather than `CallbackTo` (recalculate). Also, probably like you described, everything ends up as a `CallbackTo`, while it really... isn't a callback (at least yet). it's something that can change while you're not looking.
It would probably be a big departure from the current way of doing things, but couldn't we just instantiate a new `Backend` after `componentWillReceiveProps` (at least if `oldProps ~/~ newProps`) and get rid of the whole problem by always accessing unwrapped `Props` and thus pretend they are immutable, as far as the `Backend` is concerned?
* + Cumbersome access to `State` feels like a push in the right direction. There is generally not a big need to read it (outside of things that ends up as a callback anyway), and `modState` works the same as before.


> I think it will be nice if I use a macro to have ReactComponentB discover the backend's render fn, figure out the needed arguments (any combination of P, S, PropsChildren) and supply it automatically.

Nice to have, but `.render($ ⇒ $.backend.render($.props, $.state))` certainly isnt the end of the world

> I think lifecycle scopes can just return props/state directly without a problem.

You mean access props/state? Everything that can be thought of as an event handler which cannot save state should just be given unwrapped versions i think.

> I think methods like forceUpdate should be wrapped in callback only when setState is.
:+1: 

I don't have any real input for the last two points for now. Components as classes will definitely need some thought, but I have no idea how it will end up.

**Comment by elacin** [comment]
ref instantiating new Backends, it seems to [work](https://github.com/elacin/scalajs-react/commit/e16740807b873e3dc225e6aa5870bdb0761f5aad) at least, though i dont know if its a good idea

**Comment by japgolly** [comment]
Legitimate use of `.{props,state}: {P,S}` in `BackendScope`: `Px.thunk{A,M}`.

If we make `.{props,state}: CallbackTo[{P,S}]`, we'll probably need to add `.{props,state}Px{A,M}: Px[{P,S}]` which would have to be provided by an implicit class in extra.

**Comment by japgolly** [comment]
And/or maybe natural transformations from `CallackTo ~> Px`.

**Comment by japgolly** [comment]
No wait I'm wrong. You wouldn't want a `Px[Props]`, you'd want finer-grained `Px`s that use appropriate `Reusability`. Hmm, maybe there should be a way to map from `Px` and have a 2nd `Reusability` guard that checks the result...

**Comment by japgolly** [comment]
@elacin Thanks as always for the input. It's appreciated.

> At this point i barely see why render() should live in a Backend and have any special access at all.

I replied in the other thread to that :)

> Access to Props is cumbersome and feels a bit wrong.

Is it? In which context? `render()` will receive it unwrapped, for everything else in Backend it's often a bug not to.

> It would probably be a big departure from the current way of doing things, but couldn't we just instantiate a new Backend after componentWillReceiveProps (at least if oldProps ~/~ newProps) and get rid of the whole problem by always accessing unwrapped Props and thus pretend they are immutable, as far as the Backend is concerned?

That would be super bad for most of the backends I write. I rely on the same instance being used for the duration of the component's mounted life. I often store many `val`s and `Px`s in there and it's very efficient. Large complex UIs that I've heard are slow in prod are fast in my dev-mode before any optimisation and using dev-mode React. You could have what you described by putting this in your backend `val p = Px.thunkA($.props); val b2 = p.map(new PropsScopedBackend(_))` and if you wanted it everywhere you could use a trait to cut down the boilerplate.

Oh and `ReusableFn`s rely on this property too. All of my `ReusableFn`s are created as `val`s in backends and thus they gain reusability for duration of the component's mounted life.

> Nice to have, but .render($ ⇒ $.backend.render($.props, $.state)) certainly isnt the end of the world

Yeah true, but I would get annoyed writing that all the time - I hate boilerplate. If it's going to be common I'll find a way to make it nicer :)

**Comment by japgolly** [comment]
This is the way it looks to be going:

| Method | `BackendScope` | During Callback | External Access |
| --- | --- | --- | --- |
| `.props` | `CallbackTo[P]` | `P` | `P` |
| `.state` | `CallbackTo[S]` | `S` | `S` |
| `.setState` | `Callback` | `Callback` | `Unit` |
| `.modState` | `Callback` | `Callback` | `Unit` |
| `.forceUpdate` | `Callback` | `Callback` | `Unit` |

**Comment by elacin** [comment]
Yeah, guess that was a too coarse grained approach - tempting as i found it. Having a place to save   cached values across `Props` updates is indeed useful.

> This is the way it looks to be going:

Looks good! This completely fixes one of the major problems with the library. Great job!

**Comment by japgolly** [comment]
> Looks good! This completely fixes one of the major problems with the library. Great job!

Woah, cool thanks, nice to know you feel that way. Hopefully this will make our code much more reliable and still easy to use.

**Comment by japgolly** [comment]
Got this working on a branch. Created a branch in my work project to test it out - 120 errors :(
Browsing the errors, many quick fixes but also a genuine number of bugs, mostly in all the earlier components when my experience was low.

I'm sorta not happy about the extra complexity this adds but it looks like it's worth it.

> Looks good! This completely fixes one of the major problems with the library. Great job!

Thanks @elacin ! Your comment suggests I'm not going crazy when I see a need for this, which is what I sometimes feel :D

**Comment by japgolly** [comment]
Finally done in 0659d8800c208518c0b62dde40bc953061f83b33
