### ISSUE TITLE
RFE: Add support for setting/getting the child context

### ISSUE THREAD

**Issue by ebruchez** [japgolly/scalajs-react#220]
I have a use case where my components recursively depend on an implicit evaluation context, and it seems that this relatively new feature would help. See https://facebook.github.io/react/docs/context.html.

**Comment by zlangbert** [comment]
+1

Was just wishing I had this yesterday.

**Comment by ebruchez** [comment]
As a workaround until there is proper support, I found out that you can use `configureSpec()` on the builder to add custom properties on the component , including `childContextTypes` and `getChildContext`.

**Comment by japgolly** [comment]
Written in big, dangerous  red:

> Context is an advanced and experimental feature. The API is likely to change in future releases.
Most applications will never need to use context. Especially if you are just getting started with React, you likely do not want to use context. Using context will make your code harder to understand because it makes the data flow less clear. It is similar to using global variables to pass state through your application.
If you have to use context, use it sparingly.
Regardless of whether you're building an application or a library, try to isolate your use of context to a small area and avoid using the context API directly when possible so that it's easier to upgrade when the API changes.

"Experimental feature", "likely to change", "similar to using global variables"... It's basically an untyped component-tree-local variable. This doesn't sound like something that should be supported here.

In fact, it doesn't seem like something that *can* be supported in Scala. The gymnastics required to make this type-safe would be crazy. And then Facebook would just remove it or change it. I'd have to support it forever.

I think if you're going to use Scala, just pass props from parent to child. We have enough tools in Scala-land to do it without a high cost, and then it's all nice and type-safe so you know it works and will survive refactorings in future.

**Comment by ebruchez** [comment]
Point taken regarding the experimental nature of this API and the type-safety. Since there is `configureSpec()`, I can live with this not being implemented as I experiment with it.

**Comment by zlangbert** [comment]
Fair enough. I could see why support wouldn't be so easy. I think there are use cases though. If I want some theme object to available to all my components so they can style themselves, putting it as part of the props for every single component (even if its passed implicitly) is cumbersome imo

**Comment by japgolly** [comment]
Yeah I know what you mean about it being a bit more cumbersome. Be careful if you go down that route though, you'll create dependencies that `scalac` doesn't know about and can't verify. It might save you 30 sec per component writing you're writing them but when you refactor things in future or change the layout so that the component tree is different you can very easily end up with runtime errors that you will go undetected at compile-time. Take care if you stick with this :)

As you still have `configureSpec()` to use this if you wish, I think we can close this for now.

**Comment by nghuuphuoc** [comment]
> As a workaround until there is proper support, I found out that you can use configureSpec() on the builder to add custom properties on the component , including childContextTypes and getChildContext.

@ebruchez Can you give me a snippet of code?

**Comment by ebruchez** [comment]
@nghuuphuoc Sorry I ended up not using `configureSpec` and don't have a snippet readily available.
