### ISSUE TITLE
Make BackendScope covariant on State (and Props?)

### ISSUE THREAD

**Issue by rpiaggio** [japgolly/scalajs-react#243]
If a component's State is `Option[T]` and we define `.initialState(None)` we get an error:

`[error] Note: None.type <: Option[T], but trait BackendScope is invariant in type State.
[error] You may wish to define State as +State instead. (SLS 4.5)`

**Comment by elacin** [comment]
It's not necessary, and might not even be wanted. You can just specify explicitly that your state should have a less specific type than `None.type` - this is more of a scala type inference issue, imo.

```scala
.initialState[Option[T]](None)
```

**Comment by japgolly** [comment]
(Going off memory rather than looking at code), neither covariance or contravariance will compile. Prove me wrong if I am wrong :)

Another solution is:
```scala
.initialState(None: Option[T])
```

It's the same in this case but can be superior in cases where there are multiple type params and scalac is only having trouble with a subset of them.

**Comment by japgolly** [comment]
Closing this issue for reasons above.

**Comment by nafg** [comment]
Another solution is `.initialState(Option.empy[T])`
