### ISSUE TITLE
ExternalVar does not provide read access to an external variable

### ISSUE THREAD

**Issue by edmundnoble** [japgolly/scalajs-react#319]
`ExternalVar` allows you to encapsulate a variable's value at *construction time*, and yet set the variable's value at the *current time*. This allows for awkward things like: setting an ExternalVar cannot change its value. This makes ExternalVar unusable for practical information propagation. What ExternalVar needs to fix this is a `getter: () => A` constructor param instead of `value: A`.

**Comment by japgolly** [comment]
Hi @edmundnoble. That's very much by design and a desirable property. If getter were an impure `() => A`, your code becomes hard to reason about (these days I have pretty much no impure functions anywhere in my code and after a lifetime of doing it the other way, purity makes coding a bugfree dream). Not only that, it's not The React Way and you lose the chance to help React avoid meaningless vdom renders and diffs. Better to pass in pure fns & immutable values to components.

(As a sidenote, a pure fn in the shape of `() => A` is identical to just `A`.)

**Comment by edmundnoble** [comment]
@japgolly `ExternalVar` has an external *setter*, though. It clearly is modelled for external access to a variable, and provides side effects acting on that variable; if that variable is only settable, why not just call it `Consumer`?

The reason I want this is for pull-based access to resources. Not all resources in my app justify this approach, but certain ones like configuration I prefer not to push directly but to pull at deterministic points of my program.

**Comment by japgolly** [comment]
It doesn't contain side-effects. The `set` type is `A => Callback` which is pure. Provide it a new `A` and you will get a deterministic `Callback` instance. You don't execute the `Callback`, you provide it to React which provides it to DOM to be executed in an event *callback*. If you provided `get` as `CallbackTo[A]` it would make no sense because React needs access to `A` now (during the render fn) which is pure.

If you want to pull-based access feel free to create you own helpers but some words of advice, you'll be creating a breeding ground for bugs, especially later once you're happy with the code you've written and want to move on. React will have no way of knowing when a pulled value needs refreshing, you'll likely find that parts of the page don't update sometimes. It goes against purity and it goes against React's unidirectional flow.

**Comment by edmundnoble** [comment]
Oh, I think I misunderstood the intended use of `ExternalVar`. It's for modifying something that will re-render the component? And it's our responsibility to make sure that happens or it won't work correctly? If you are making the assumption in your `ExternalVar` definition that the setter *must* affect the current component's state, then that wasn't obvious from the comments. "Provides a component with safe R/W access to an external variable" is misleading IMO if it is in fact for access to a variable that, on set, will re-render the component.

I can understand your reluctance to add pull-based tools, no reason to make `ExternalVar` something it isn't. I can probably adapt my approach to work this way.

**Comment by japgolly** [comment]
Yes, that's exactly it. Reading and understanding your PoV makes me realise how much implicit.... uh.. "information" I assume readers have. This is why authors writing docs doesn't always lead to the best result :laughing:. Thanks.

Are you ok to close this issue?

**Comment by edmundnoble** [comment]
Absolutely, if you think adding to the docs is warranted I'll be in the chatroom if you'd also like feedback. For now, closing.
