### ISSUE TITLE
Rename ScalaComponent.build to ScalaComponent.builder

### ISSUE THREAD

**Issue by netzwerg** [japgolly/scalajs-react#334]
First things first: The new release is very impressive – congratulations. I am really grateful for the amazing work you are doing!

One thing I personally find confusing in the new API is the name of the `ScalaComponent` entry point:

```scala
def build[P](name: String) =
    new ScalaBuilder.Step1[P](name)
```

Maybe this is just my Java past, but renaming `component.Scala.build` to `component.Scala.builder` would add clarity. IMHO, the `build` method name should be reserved for the final creation of the component, i.e. marking the end of the fluent building chain.

**Comment by japgolly** [comment]
Thank you! I appreciate your appreciation :D It always makes me happy to know that my work makes other people's lives a bit happier. :blush:

That's a really good point. Seeing `.builder` → `.build` should read more clearly than `.build` → `.build`. My original thought was that the initial `.build` was appropriate because it's like a command, a verb. My only hesitation is that with `builder` being a noun it applies that it might return a meaningful result that you can pass around. By the time you get a result you've already specified two data (props and name).

That being said I think `.builder`  → `.build` will be clearer regardless.
Maybe I should change it to something like:
```scala
// in .internal
object ScalaBuilder {
  def apply[P](name: String) = new Step1[P](name)
}

object ScalaComponent {
  def builder = ScalaBuilder
}
```

Thoughts?
Anyway let's let it ruminate for a few days.

**Comment by netzwerg** [comment]
> By the time you get a result you've already specified two data (props and name)

This is the classic builder pattern, no? Creating the builder always requires specification of all mandatory data.

I like your suggested API changes 👍

**Comment by japgolly** [comment]
Ok, done. Let me know what you think. There's a little migration script too in `doc/changelog/1.0.0-RC.md`.

**Comment by netzwerg** [comment]
Awesome, thank you – I will give it a spin!
