### ISSUE TITLE
Please add some docs to User facing api,eg japgolly.scalajs.react.component.ScalaBuilder

### ISSUE THREAD

**Issue by hepin1989** [japgolly/scalajs-react#336]
Thanks a lot,this work will definitely help new comers like me,the `Stepx` and its method etc.

**Comment by japgolly** [comment]
Hi @hepin1989, From my perspective the parts of the API that need doc have it and in many cases I don't see the need because the types explain better than doc. It's always a bit hard for the author to see where doc is necessary and also whether it's adequate or not. I think it would be better for users to help by submitting PRs to increase the doc where they consider it helpful.

**Comment by japgolly** [comment]
Closing because not quantifiable but I will keep your words in my mind, @hepin1989

**Comment by japgolly** [comment]
Added a bunch of ScalaDoc to the Scala component builder: 2af018c60577782cd511624fb48c5a290679f8cb
/cc @hepin1989
