### ISSUE TITLE
$.zoom... ?

### ISSUE THREAD

**Issue by joan38** [japgolly/scalajs-react#362]
Hi,

I saw that we can do stuff like `$.zoom...` in this doc https://github.com/japgolly/scalajs-react/blob/master/doc/USAGE.md#react-extensions

Unfortunalty I was not able to find the `zoom` function on `$`, so either it doesn't exist anymore then the doc is outdated, or I'm missing an import or a dependency then the doc is not precis enough or I'm mistaken.

In any case I'm happy to update the doc according to the solution :)
Thanks again for this amasing library, this is awesome!

**Comment by japgolly** [comment]
Oops, it looks like that snippet of doc is out of date, it's now `zoomState` instead of `zoom`.
The methods are [here](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/StateAccess.scala) (which all components extend, [see](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/Generic.scala#L95)).

You can also see a similar [example/demo here](https://japgolly.github.io/scalajs-react/#examples/state-snapshot) that uses Monocle.

> Thanks again for this amasing library, this is awesome!

Thank you! I'm glad to hear you're enjoying it :smiley:

**Comment by joan38** [comment]
@japgolly Thanks for your answer.
But I still can't access `zoomState`, do you see what's wrong here:
```
def component[Params <: HList, ParamValues] =
    ScalaComponent
      .builder[Props[Params, ParamValues]](getClass.getSimpleName)
      .initialState {
        val taskInfo = Task.Info(runId = RunId.newId())
        (taskInfo, Map[String, Any](RunId.name -> taskInfo.runId))
      }
      .renderP { ($, props) =>
        def runTask = Callback.alert(s"""RunId: ${$.state._2}
                                        |Parameters: ${props.values($.state._2).toString}
                                        |""".stripMargin)
        //Callback(AutowireClient[Api].runTask('ahah).call())

        $.zoomState()
        val displayState = Displayer.State(kv => $.modState(s => s.copy(_2 = s._2 + kv)), key => $.state._2.get(key)) // TODO: Make it better with lenses

        <.div(
          <.div(props.name),
          props.displays(displayState),
          <.button(^.onClick --> runTask, "Run")
        )
      }
      .build
```

**Comment by joan38** [comment]
I found the code of the exemple: https://github.com/japgolly/scalajs-react/blob/master/gh-pages/src/main/scala/ghpages/examples/StateSnapshotExample.scala#L14
But can't seems to be the same thing.

**Comment by japgolly** [comment]
Ah right, that's cos you're working with [`RenderScope`](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/component/builder/Lifecycle.scala#L224-L232).
Try using `$.mountedPure.zoomState`

**Comment by joan38** [comment]
Nice it worked thanks @japgolly
