### ISSUE TITLE
Use StateSnapshot in conjunction with a Backend

### ISSUE THREAD

**Issue by i-am-the-slime** [japgolly/scalajs-react#370]
My `render` method was getting very big, it especially had quite a few functions that were defined inside of it. So I tried to make a Backend.

Now I get this:
```scala
could not find implicit value for parameter t: japgolly.scalajs.react.StateAccessor.ReadImpureWritePure[japgolly.scalajs.react.BackendScope[ProcessListPage,BigState],BigState]
[error]       val statusesV = StateSnapshot.zoomL(_processStatuses).of($)
[error]                                                               ^
```

Is this even possible?

**Comment by japgolly** [comment]
That error is correct because `BackendScope` is pure R/W access, not impure-R/pure-W. (And it's a good thing we have these types or else it would've introduced a bug in that prevented reusability working. Good job types!)

If you don't care about reusability, instead of using the `BackendScope` instance, you could pass in the `RenderScope` through your render function and then just use that like you were before.

If you want reusability, you'll want to prepare the write-fn as a `val` in the backend and then use *that* in the render function to arrive at a `StateSnapshot`. See https://github.com/scalacenter/scastie/pull/202/files for an example of that.

**Comment by japgolly** [comment]
Question: Answered. Closing.
