### ISSUE TITLE
Help with porting scalajs-react-bridge

### ISSUE THREAD

**Issue by ramnivas** [japgolly/scalajs-react#385]
Not exactly an issue, but I am trying to get types right while porting [scalajs-react-bridge](https://github.com/payalabs/scalajs-react-bridge/tree/neo). I have it basically ported and all tests are passing, but I am not sure about the [types I have used](https://github.com/payalabs/scalajs-react-bridge/blob/neo/src/main/scala/com/payalabs/scalajs/react/bridge/ReactBridgeComponent.scala#L50) and I am facing one issue where I can use your help/pointers.

I will like these components to behave similar to `div` (of type `TagOf[_]`). Specifically, I will like to use components such as `TestComponent` in [tests](https://github.com/payalabs/scalajs-react-bridge/blob/neo/src/test/scala/com/payalabs/scalajs/react/bridge/test/ReactBridgeComponentTest.scala#L31) passing it arbitrary `TagMod`s (such as `onClick`, `onDoubleClick` etc). In other words, I will like to be able to instantiate component in the following way:
```scala
   val testComponent = TestComponent(key = "mykey")(onClick --> someCallback)
``` 
However, when I do that in my testsuite (as well as real components outside this project), the resulting type for such an expression is `TagMod`. It looks like there is no implicit conversion from `TagMod` (unlike `TagOf`) to `VdomElement` (which perhaps is intended). As as result, I can't do `val mounted = ReactTestUtils.renderIntoDocument(testComponent)`.

I also suspect that I am overdoing things with [`ComponentNoChild`](https://github.com/payalabs/scalajs-react-bridge/blob/neo/src/main/scala/com/payalabs/scalajs/react/bridge/ReactBridgeComponent.scala#L51) and may not actually need it. I am not actually particularly keen on prohibiting children for certain components, but more interested in not requiring an additional set of `()` for component instances that don't wish to pass children.

Thanks for your help.

**Comment by japgolly** [comment]
Hi @ramnivas, that's a big blob of macro code and unfortunately I don't have the time to look at it deeply so I won't be able to give you too direct an answer. Instead let me say some brief points:

* `TagMod` cannot be automatically turned into a `VdomTag` or `VdomElement`. That's because you can't ask React to render `{onClick: fn}`. It needs to modify a tag like `<div>` which would then result in `<div onClick=fn>`.

* You might not need macros anymore (I wasn't too thorough in my quick read of your code). Once you have a basic underlying React component you can now transform the hell out of it, *everything*, the props, the state, results when mounted and unmounted, the constructor. Transforming can be mapping, or providing defaults or additional data, making dynamic choices. Components built by `ScalaComponent.Builder` take this approach and require no special treatment from the library anymore. Might simplify what you're doing. Check out [doc/TYPES.md](https://github.com/japgolly/scalajs-react/blob/master/doc/TYPES.md)

* Re: `ComponentNoChild`, this distinction is supported by scalajs-react now. You don't need your own representation (or hack :smile: ); you can get exactly what you described out-of-the-box by having the appropriate `CtorType` in your component. (Again, see [doc/TYPES.md](https://github.com/japgolly/scalajs-react/blob/master/doc/TYPES.md), it's abbreviated as just `CT` as a type param once you're past its definition in that doc)

Good luck. If you'd like more specific help, if you can provide a really small snippet I can be more specific. Cheers

**Comment by ramnivas** [comment]
Thanks for the pointers. I will look into those (and if needed, I will try to provide a macro-free snippet to carry focused discussion). But for now, I want to discuss the need for the macros. I actually will love to get rid of those (with neo, the boilerplate required is substantially reduced; so in fact, at first I tried to do without the macros, but felt that it still needed some boilerplate that I will like to avoid).

Case in point, I am trying to create scalajs-react facade over [Material Design Component](https://github.com/material-components/material-components-web) through https://github.com/kradio3/react-mdc-web. When it is all done, I expect to have about 200 or so components, so boilerplate-freeness is going to matter a lot (especially given that both the underlying libraries are going through a constant change). 

With scalajs-react-bridge, I am able to do the following.

```
object Card extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String], onDoubleClick: js.UndefOr[Callback] = js.undefined): Component = this.autoConstruct
}

object CardHeader extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String] = js.undefined): Component = this.autoConstruct
}

object CardTitle extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String] = js.undefined): Component = this.autoConstruct
}

object CardText extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String] = js.undefined): Component = this.autoConstruct
}

object CardActions extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String] = js.undefined): Component = this.autoConstruct
}
```

This is working (sans the issues I raised). If you see any macro-free way to achieve something close, please let me know.

**Comment by japgolly** [comment]
Ah that's very cool. I don't have a problem with macros but thanks for making it obvious to me how/why you're using them. I don't know of a way to achieve that much boilerplate reduction without macros.

In which case, to help answer your question, let's just focus on one case, say:
```scala
object Card extends ReactBridgeComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[String], onDoubleClick: js.UndefOr[Callback] = js.undefined): Component = this.autoConstruct
}
```

It's the generated code you're asking about, right? What will your macro expand the above to, if you paste I can review it and give suggestions.

**Comment by ramnivas** [comment]
Here is the equivalent macro-less code (use `BaseComponent` to reduce per-component boilerplate). The macro does one more thing of mapping Scala collections and callbacks into their Js equivalent, but that is not super relevant here.

```scala
class BaseComponent {
  private val RawComponent = js.Dynamic.global.selectDynamic(this.getClass.getSimpleName)

  protected val component = JsComponent[js.Object, Children.Varargs, Null](RawComponent)

  protected def create(props: js.Object, key: js.UndefOr[Key] = js.undefined) = {
    component.mapCtorType { c =>
      val withProps = c.withProps(props)
      key.fold(withProps)(k => withProps.withKey(k))
    }
  }
}

object Card extends BaseComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[Key], onDoubleClick: js.UndefOr[Callback] = js.undefined) = {
    val jsProp = js.Dynamic.literal(className = className)
    onDoubleClick.foreach { cb =>
      jsProp.updateDynamic("onDoubleClick")(() => cb.runNow())
    }

    create(jsProp, key)
  }
}
```

With this setup, I can do:
```scala
Card(className = "block-short-view", key = height.toString, onDoubleClick = onViewDetails)(
  div(...)
)
```
What I will like to do is (something close to) the following:
```scala
Card(className = "block-short-view", key = height.toString)(onDoubleClick --> onViewDetails)(
  div(...)
)
```

The reason being that for most components all DOM attr/callbacks can be relevant in addition to the specified properties (here for example, onClick, onHover etc. could be quite useful).

**Comment by japgolly** [comment]
Firstly, you don't need to worry about the explicit `key` handling and doing `key.fold(withProps)(k => withProps.withKey(k))`. It's a bit of a dirty secret but at the moment, applying a `key` to a `js.Object` prop will modify it directly rather than creating a copy. See [this](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/CtorType.scala#L237-L255) and [this](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/CtorType.scala#L25-L29). (This doesn't affect ScalaComponents)

To the heart of your question I'm not sure what you mean. I think you mean you want to create a component like `Component(props*)(attr*)(children*)` so that you don't need to include all possible vdom attributes as props? Hmmm.... not really possible out-of-the-box. You could collect a bunch of `TagMod`s and then using `.applyTo(Builder)` provide your own [builder](https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala#L84-L88) to make it add the styles and attributes to your props object. The problem is though, that `TagMod` is anything that can modify a tag which includes adding children. Maybe you could have your custom builder extract the children and then pass them to the underlying JS component separately as children. That could work. Then you'd declare your attributes as `Children.None` instead of `Children.Varargs` and have your own custom apply in the shape of:
```scala
  def apply(prop1: js.UndefOr[String] = js.undefined,
            prop2: js.UndefOr[Int]    = js.undefined)
           (attrAndChildren: TagMod*): VdomElement
```

**Comment by ramnivas** [comment]
Thanks for your response. I truly appreciate your time in helping here.

Re: Key. Good to know. I will adjust the code accordingly.

Actually, you understood it correctly. I want to be able to specify component-only props with `props*` and allow for the possibility of any vdom attrs as `attr*` and possibly children (depending on the component). As I was working through Material Design Component, I came to a realization that supporting an ad-hoc set of vdom attrs for each component isn't sustainable. When I looked at `TagOf`'s such as `div`, I could see that it is legal to do `div(id := "myid")(className := "mycls")(...children...)`. The type of this expression is still `TagOf` (which can then be turned into a `VdomElement` through [ImplicitsForVdomElement](https://github.com/japgolly/scalajs-react/blob/cb75721e3bbd0033ad63d380bcaddc96fbe906e3/core/src/main/scala/japgolly/scalajs/react/vdom/Implicits.scala#L94)). I wondered if I could do the same with bridged components.

All this is to say, if you can think of any other possibility that can address this need (or find issues with this need), please let me know. The exact form isn't crucial here as long as it let's me address the general need neatly.

I will try to grok builder and a possibility of a custom builder to see how far I can take it. Do you have an example of a custom `Builder` that I can look as an example?

**Comment by japgolly** [comment]
No worries, I'm happy to help but I've got *a lot* going on in my life right now so unfortunately there may be large gaps of time between my responses. Such is life.

I'll have a look at making that builder I have in mind. It could be useful in a general sense...

**Comment by japgolly** [comment]
@ramnivas Ok I just pushed a change to master, take a look [at this](https://github.com/japgolly/scalajs-react/blob/7ab69eb92a8e2afc595fa60b6057d7a50368c1ea/core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala#L42-L55). If you use that builder then you get easy access to props/style/children as raw JS objects.

I'll probably add a method for this soon but for now, you can use it like this:
```scala
val myVdom: TagMod = ...
val b = new Builder.ToJs{}
myVdom.applyTo(b)
// now use the results
b.addStylesToProps()
b.props // js.Object
b.nonEmptyProps // js.UndefOr[js.Object]
```

**Comment by ramnivas** [comment]
Thanks.

I tried and experimented to understand how I can use it to do what I want, but I don't really grok this. For example, if I change the `Card` definition above to (basically adding a curried param for `TagMod`s):

```scala
object Card extends BaseComponent {
  def apply(className: js.UndefOr[String] = js.undefined, key: js.UndefOr[Key])(attr: TagMod*) = {
    val jsProp = js.Dynamic.literal(className = className)
    create(jsProp, key)
  }
}
```

Where can I bring in the `Builder.Js` builder to use `attr`?

**Comment by japgolly** [comment]
Like this:

```scala
    val RawComponent = js.Dynamic.global.Blah
    val Component = JsComponent[js.Object, Children.Varargs, Null](RawComponent)

    @js.native
    trait SpecialProps extends js.Object {
      var prop1: js.UndefOr[String] = js.undefined
      var prop2: js.UndefOr[Int]    = js.undefined
    }

    def apply(prop1: js.UndefOr[String] = js.undefined,
              prop2: js.UndefOr[Int]    = js.undefined)
             (attrAndChildren: TagMod*): VdomElement = {

      val b = new japgolly.scalajs.react.vdom.Builder.ToJs {}
      attrAndChildren.toTagMod.applyTo(b)
      b.addClassNameToProps()
      b.addStyleToProps()
      val p = b.props.asInstanceOf[SpecialProps]
      p.prop1 = prop1
      p.prop2 = prop2
      Component.apply(p)(b.children.toList.map(a => ??? : VdomNode): _*)
    }
```

It's a bit messy but I'll clean up usage before the next release. I also couldn't get the children to work, hence the `???: VdomNode`. Just ignore that bit for now, when I work on this bit properly I'll fix that.

**Comment by japgolly** [comment]
Updated. This will be released in v1.1.0, probably today.

New usage:

```scala
    val RawComponent = js.Dynamic.global.Blah
    val Component = JsComponent[js.Object, Children.Varargs, Null](RawComponent)

    @js.native
    trait SpecialProps extends js.Object {
      var prop1: js.UndefOr[String] = js.undefined
      var prop2: js.UndefOr[Int]    = js.undefined
    }

    def apply(prop1: js.UndefOr[String] = js.undefined,
              prop2: js.UndefOr[Int]    = js.undefined)
             (attrAndChildren: TagMod*): VdomElement = {

      val b = attrAndChildren.toTagMod.toJs
      b.addClassNameToProps()
      b.addStyleToProps()
      val p = b.props.asInstanceOf[SpecialProps]
      p.prop1 = prop1
      p.prop2 = prop2
      Component(p)(b.childrenAsVdomNodes: _*)
    }
```

**Comment by japgolly** [comment]
@ramnivas Can we close this now?

**Comment by ramnivas** [comment]
@japgolly This looks great. Thanks!

**Comment by japgolly** [comment]
Awesome, enjoy!

**Comment by ramnivas** [comment]
FYI and thanks!

This new version supports 'neo' and utilizes your improvements here.

https://github.com/payalabs/scalajs-react-bridge
