### ISSUE TITLE
Get router page from RouterCtl

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#390]
on the router client API `RouterCtl[A]` I don't see a way to get the current page from `RouterCtl`. Is that possible?

**Comment by japgolly** [comment]
No not possible. `RouterCtl` is contrvariant to A, A's go in but don't come out, if they did it would be invariant and that would be terrible because it would impose other restrictions that would prevent you from doing the things that it does well. Plus you'd be locking read/write in conflation. Better for R/W to be separate with `RouterCtl` being W, and you just passing the current page around yourself for R.

**Comment by cquiroz** [comment]
Ok, thanks I'm using the methods that pass a page to do that like `dynRenderR`

**Comment by japgolly** [comment]
Sounds good. I think I'm doing the same in one of the modules in my main project too
