### ISSUE TITLE
Websocket example does not catch connection errors

### ISSUE THREAD

**Issue by Tamriel** [japgolly/scalajs-react#408]
The websocket [example](https://japgolly.github.io/scalajs-react/#examples/websockets) tries to catch connection errors somehow with
```
connect.attemptTry.flatMap {
      case Success(ws)    => $.modState(_.log("Connecting...").copy(ws = Some(ws)))
      case Failure(error) => $.modState(_.log(error.toString))
    }
```
But when I change the server url to something faulty like e.g. `wss://echo.websocket.orgggg` the occurring runtime exception is not logged. Maybe it needs to be catched with a `try`, like in this [example](https://github.com/monix/monix-sample/blob/19b555626061d3ac5a9a95a233dd6cab6698b539/client/src/main/scala/client/SimpleWebSocketClient.scala#L42)?

**Comment by japgolly** [comment]
Hi, I had a look at this this morning and the problem occurs even with `.attempt` (which using `try`/`catch` like you suggest). The problem is that `new WebSocket(url)` doesn't throw an exception. It logs the error to the console and then returns as if nothing is wrong. Very annoying. I think the only way to tell that it failed is that `.readyState` never reaches `WebSocket.OPEN`.

**Comment by japgolly** [comment]
Added the appropriate error handling in da1738464cac469dcf8d19ebc399a372837dec06
