### ISSUE TITLE
Support for styled components?

### ISSUE THREAD

**Issue by hejfelix** [japgolly/scalajs-react#428]
I have been using the macros from [scalajs-react-components](https://github.com/chandu0101/scalajs-react-components) to create my facades, but using those macros I have no control over how the props get passed into the components.

I want to achieve something similar to https://github.com/styled-components/styled-components but I'm not sure how to go about this. Any ideas on how to achieve this?

**Comment by japgolly** [comment]
That would be very cool and it's part of my planned future for ScalaCSS. Unfortunately, I won't have the time for such a feature for a long while. It's totally possible though: you would create/find a CSS parser from Scala and call it at compile-time from a macro.

I'm going to close this issue here because it's a nice-to-have feature request that isn't going to be implemented for a long-time. If you'd like to pursue it feel free to submit a PR, it would be very welcome. We can also discuss it further here despite the closed status.
