### ISSUE TITLE
Thoughts on making scalajs-react even more modular?

### ISSUE THREAD

**Issue by nafg** [japgolly/scalajs-react#488]
There are a number of different libraries for doing React in scala.js. It would be nice if they were less mutually exclusive. Of course since it's all the same javascript underneath interop is just a matter of some casting hidden inside a typesafe method, but perhaps it could be improved.

The main defining difference seems to be "how to define and use a component." Different libraries take different approaches, which is great. However some of the other differences seem secondary.

1. I'm guessing that the low-level facade stuff is mostly the same. If that were its own module perhaps the code could be shared, making interop more trivial. I don't know what the status is of https://definitelyscala.com/ but it would be interesting if the low-level facade could just be auto-generated from the official typescript definitions.
2. There are a few high-level VDOM APIs. Scalajs-react uses the TagMod abstraction which has amazing composability possibilities because you can always add more attributes and children. On the other hand Sri used an API with generated named args for attributes, which suggests more type safety because each element can only take attributes it supports. Perhaps other approaches can be created (I have some ideas if I ever have time for them!). If the VDOM APIs could be orthogonal to everything else, a new VDOM API could be written to work with any React library.

**Comment by japgolly** [comment]
Hi @nafg thanks for the write up but I'm sorry to tell you I don't see this happening:

1. There is already a means of interop. One can use JS components in scalajs-react, and one can export scalajs-react components and use them in JS (I've done both). In terms of interop between scala.js libraries we already have an interop protocol which is JS components.

2. I think you'll find the low-level facades are quite different. I believe this is the most type-focused of the scala.js react libraries and would be the most hurt or inconvenienced by a common facade. I certainly don't want to be submitting PRs when I need to encode more React concepts in facade types, especially for subtle stuff.

3. VDOM API synchronisation would be nice in theory but really I don't see much practical value in. Who's jumping around between libraries copy-pasting their vdom? More importantly though, it will take time and effort to create an agreed API, then more process when one library wants to add a feature, especially an vdom-orthogonal one. I don't have the time, motivation, nor the belief in the benefit. If someone else were willing to do ***all*** of the work and address my concerns then that's different story.

**Comment by nafg** [comment]
Hi, thanks for the response. I'm not sure if I was unclear or I'm not understanding your response, so to clarify:

1. By interop I mean e.g. between scalajs-react, Slinky, react4s, and Sri.
2. By low-level stuff I mean the raw types, that are typically not part of the public API
3. Re decoupling Vdom, I'm not trying to advocate for coming to some common API. I guess there would have to be some shared raw type that you would have to drop down to, not sure.

Also, in general if I float an idea, l don't mean it as a request for you to implement it, it just means I'm wondering whether it makes sense and what would doing it would involve exactly. (I think you said you prefer to have that level of discussion here rather than e.g. on Gitter.) Of course, once an idea is fleshed out if no one implements it the conversation may seem to have served no purpose, but I think it's still worth discussing -- either it will turn out to be a bad idea, in which case at least I'll have learned something, or maybe someone will want to implement it (potentially me), or else at least I'll have gained clarity, and it might serve as food for thought for the future. So in short, I hope I don't come across as asking you to do stuff for me. :)

**Comment by nafg** [comment]
Also, since your facades are probably the most thought at and used for the longest, I would expect that even without making any change at all other than breaking it up into separate artifacts, other react facade libraries would be happy to use the raw API as is rather than reinventing the wheel. If you're open to considering that I could find out whether that's the case.

**Comment by valenterry** [comment]
@japgolly what do you think about the idea? I think it is a very good one and the effort should not be too high because it is mostly splitting up things, making it easier to keep up to date with react API changes and minimizing dependencies.

**Comment by japgolly** [comment]
Sounds like lots of work which rules it out for me doing it for a while, even if I were convinced (which I'm not really). If someone wants to put their hand up to do the work I'll pay proper attention so I can guide the effort.

To clarify are we talking about more sbt modules, or are we talking about separate libraries with their own release cadance?

**Comment by nafg** [comment]
I don't see a reason to have a separate release cadence. So if different
packages already don't have cyclic dependencies I think it would just be a
matter of moving different packages into different source directories and
defining them in sbt.

**Comment by valenterry** [comment]
I agree with @nafg. The main point is to decouple things a bit and also make it easier to reuse parts and contribute to them (because of a more limited scope). But I think we should only start to sketch something out of @japgolly is on board and thinks it is worth to make the effort. So far I'm just a user of scalajs-react and thought that splitting the project up would be helpful, but I'm not a good person to judge if it is really beneficial overall.

**Comment by japgolly** [comment]
> I don't see a reason to have a separate release cadence

Excellent. That would have been my main point of resistance.

> thought that splitting the project up would be helpful, but I'm not a good person to judge if it is really beneficial overall.

From my perspective there's no benefit at all. From other people's perspectives there seems to be benefit, mostly to library authors who want to provide some new functionality based on a subset of current scalajs-react, maybe to teams who want to depend on the `extra` module but don't want the router in there (even though Scala.JS will just remove it all if it's not being used). So I'm willing to be helpful to someone who wants to drive that effort. Otherwise the cost/benefit isn't high enough for me to personally drive it (you get a lot more selective when you don't have any income).

So yeah np, if either of you (or anyone else) wants to split this up a bit more (in a way that doesn't have too big an impact on end-users) then please propose, we can discuss and then go for it.

**Comment by japgolly** [comment]
Extracted a `facade` module in #926 for upcoming 2.0.0 release.

**Comment by japgolly** [comment]
Ok cool, so it turns out that I've implemented this as a necessity to effect generalisation (#928). Well actually I didn't need to extract the two facade modules but in the context of that huge refactor, and with this issue in mind, it only took me an extra 15 min so I did it.

Documentation of new modules:
https://github.com/japgolly/scalajs-react/blob/master/doc/MODULES.md

As I re-read this issue, I realise that one thing I didn't do is make the VDOM stuff pluggable. I've got some free time coming up very soon so I might give it a try, hopefully not too involving...

@nafg What do you think man? Are you happy with how this has turned out?

**Comment by nafg** [comment]
Looks amazing :)

**Comment by japgolly** [comment]
Awesome, in that case I'll close this. RC1 coming probably tomorrow
