### ISSUE TITLE
New Hooks React

### ISSUE THREAD

**Issue by nakedcity** [japgolly/scalajs-react#510]
React new hooks https://reactjs.org/docs/hooks-intro.html . Can we integrate them ScalaFnComponent
 
```
ScalaFnComponent[Props](props => {
```

**Comment by nafg** [comment]
Hooks are nice, however a couple of points:

1. Some of their motivation is less necessary in scalajs-react since we have `.configure` (so we can abstract over lifecycle effects) and `StateSnapshot` (so we can decouple pieces of state from class components)
2. To write a basic facade is probably not hard, however it would expose us to the many pitfalls and limitations that they have (only call it in the beginning of a render function, always in the same order, otherwise the abstraction leaks badly; and make sure your dependencies parameter is kept in sync with what you actually reference in the function parameter). What I'd rather see, in keeping with scalajs-react's design philosophy, is an API that lets you use hooks but that makes such mistakes impossible or much harder. For example, instead of the dependencies being a second parameter it could come first and then the function takes those values as an argument, either by doing it as a tuple or by abstracting over arity. And instead of `useXXX` being functions that you can call anywhere perhaps they should be somehow attached to how you define a component or custom hook (even if you can define a custom hook anywhere).

**Comment by nafg** [comment]
Hi any plans to tackle this in the near future?

**Comment by japgolly** [comment]
After neglecting this issue for so long (and no one submitting any PRs - don't forget this is OSS here), I have some good news. I'll be implementing this pretty soon, hopefully next week.

For any watchers of this issue: [I put out a call on Twitter](https://twitter.com/japgolly/status/1390125799949291522?s=20) that may be of interest for you:

> Would anyone be interested in watching/joining me for a live stream of me adding support for React Hooks to #scalajs-#react?
> DM me on Twitter, or email me at japgolly@gmail.com!
> I guess I'm a bit sick of covid monotony, I guess I miss social interaction, something new like this might be fun.
> Thought: what could be really cool about this is that viewers could influence the design decisions live. Noice!
