### ISSUE TITLE
Callback & CallbackTo vs Future

### ISSUE THREAD

**Issue by axos88** [japgolly/scalajs-react#526]
I saw there is an implementation of `Future[CallbackTo[A]] -> CallbackTo[Future[A]]`, but is there any reason not to have a conversion of `Future[A] -> CallbackTo[A]`?

This can currently be implemented using `CallbackTo.future(f.map(v => CallbackTo.apply(v)))`

**Comment by japgolly** [comment]
No, it's impossible to write a conversion from `Future[A] -> CallbackTo[A]` in Scala.JS because `CallbackTo` is synchronous, and there's no way to block/`Await` in JS. `CallbackTo.future(f.map(v => CallbackTo.apply(v)))` would result in a `CallbackTo[Future[A]]` and not a `CallbackTo[A]`.

Anyway, as of the last major release, all those `Callback`/`Future` conversions should eventually go in the bin. We have `AsyncCallback` now and there are conversions from `Future[A] => AsyncCallback[A]` and `AsyncCallback[A] => Future[A]`.

See:
* https://japgolly.github.io/scalajs-react/#examples/ajax-2
* https://github.com/japgolly/scalajs-react/blob/master/core/src/main/scala/japgolly/scalajs/react/AsyncCallback.scala

**Comment by axos88** [comment]
Ah thank you, that seems to answer my question. So basically instead of using Callback I need to use AsyncCallback (and convert each callback to .async when flatMapping over it), and call .toCallback at the end of the chain, correct?

One small note: I'd include an `AsyncCallback.fromCallbackTo[T](c: CallbackTo[T]) = c.async`, it took me quite a while to figure out how to convert a `Callback` to an `AsyncCallback`, as the conversion is done in the `Callback`, I expected a method to be present in the `AsyncCallback` object.

**Comment by japgolly** [comment]
Yes, that's right. A small thing though is to use `.asAsyncCallback` which is a type conversion, instead of `.async` which semantically means "make this run asynchronously" (i.e. via JS `setTimeout`). I know the names aren't the best, clear context-free discoverable names are hard to determine and there's some legacy around these to boot.

My only objection to having adding `AsyncCallback.fromCallback[T](c: CallbackTo[T]) = c.asAsyncCallback` is that now we have two ways of doing same thing. I've noticed in Scala especially that multiple (even mostly-equivalent) ways of doing the same thing lead to a lot of bikeshedding, style arguments and dev churn and so I want to minimise that in my own libraries. When choosing between alternatives I tend to prefer `a#f` instead of `f(a)` for single-argument functions as it's shorter, plays better with left-to-right module/OO method/field selection (`a.b.c`), and is more discoverable in the sense that typing `.` on data and letting the IDE provide a list of available methods is quite valuable.

Without sacrificing these benefits, how can we further improve the API? Maybe we could add `AsyncCallback.fromCallback` but mark it as deprecated with a message telling users to use `.asAsyncCallback`?

**Comment by axos88** [comment]
As I was reading your message, I was thinking exactly about adding the method as deprecated, it seems a bit meh, but would avoid the style issues you mention, but still guide the developers' hand towards the intended usage.
