### ISSUE TITLE
How hard would it be to have something like JSX?

### ISSUE THREAD

**Issue by spavikevik** [japgolly/scalajs-react#566]
Hey there, I have recently boarded the Scala train and I want to try building Scala.JS apps with React.

The current tags and attributes syntax is okay, but I find it to be slightly impractical, personally. Not wanting to imply it is bad or unusable or anything of that sort, but I honestly wish I could use something like JSX.

I just did some research, and a [similar project](https://github.com/xored/scala-js-react) to this one, seems to have implemented something called "scalax" via Scala XML literals; however, unfortunately, it no longer seems to be actively maintained.

How hard would it be to implement something like that here? If you feel it is doable, I can try to help out as much as I can.

**Comment by japgolly** [comment]
Hi and welcome aboard the Scala train!

I'm not sure hard it would be but I've got to say that personally, it's not an endeavour I'd be interesting in collaborating on (responding to *I can try to help out as much as I can.*). If you were to go down that path it would have a be a separate add-on library. I encourage you to just experimentally accept the new syntax for a while, and then see how you feel after a few weeks. Personally I find it much more practical.

Otherwise it sounds like you'd want to base it on scala-xml which is a standalone library now, and no longer part of Scala itself. I'm not sure what the plans are for it, you might want to ask around on https://users.scala-lang.org. Hope that helps!
