### ISSUE TITLE
Comparison to other scalajs react adaptions

### ISSUE THREAD

**Issue by phdoerfler** [japgolly/scalajs-react#581]
How does this library compare to [https://github.com/shadaj/slinky](shadaj/slinky)?

What do both libraries different, how are they similar, what's their focus, and so on. Thanks!

(And to what other incarnations of a scalajs version of reactjs I have missed)

Also see:
https://github.com/shadaj/slinky/issues/298

**Comment by japgolly** [comment]
scalajs-react is strongly focused on facilitating quality. To break that down further: FP, strong type-safety, an effort to make as many potential errors fail at compile-time rather than runtime, lots of support for testability, lots of support for performance "management" and optimisation.

It also comes with all kinds of utils specially crafted for the combination of the above goals, react JS, and stuff you typically need to do in a big serious webapp. Example: pure async, ajax, routing, etc etc.

scalajs-react has also seen lots of real-world usage. It's been around for many years and been deployed by many teams in many projects already. That counts as a feature because it's been hardened/battl-tested/whatever and seen lots of minor revision due to it being used to long and widely.

I won't speak to the strengths and weaknesses of other libraries; the authors and actual users are in a much better position than I am to represent those properly. I will say though that in addition to slinky there's also Sri and react4s that are (I believe) still active and going well.

**Comment by phdoerfler** [comment]
Thanks a lot for this overview, I appreciate it!

**Comment by japgolly** [comment]
No problem, I hope it helps. Happy coding whichever library you choose! :)
