### ISSUE TITLE
raw html

### ISSUE THREAD

**Issue by OlivierBlanvillain** [japgolly/scalajs-react#64]
How do you write raw html?

There use to be a raw function in ReactVDom but it looks like it's done. I'm trying to generate the following inline style: `background-position: 0px XXXpx;`, but ScalaTags does not like it :(

**Comment by japgolly** [comment]
The old `raw` function was for rendering text, but it was redundant because text is already recognised as being a valid `ReactNode`. eg. `<.div("hello")`.

For raw html we expose React's `dangerouslySetInnerHtml` attribute. eg. `<.div(^.dangerouslySetInnerHtml("<span>"))`.

If you just want to set a style, that's already supported without tricks.
`<.div(^.backgroundPosition := "0px XXXpx")`
