### ISSUE TITLE
Cross compiled Reusability

### ISSUE THREAD

**Issue by cquiroz** [japgolly/scalajs-react#699]
In most cases I keep my model in a cross compiled project as I may want to e.g. test on the jvm or share code
It would be nice to define `Reusability[A]` in `A` companion's object but for that `Reusability` would need to be cross compiled across jvm/js
What do you think?

**Comment by japgolly** [comment]
Hey @cquiroz . I've been thinking about this. I started out thinking "why not? it's harmless right?" but the more I think about it since then, well now I think actually there is harm in doing it. This is a slippery slope. First it's just `Reusability`, then maybe `Reusable` too, then maybe `Px` and maybe calls for `Callback` and `AsyncCallback` follow. You get the idea. One of the reasons I don't just cross-publish *everything* possible with this is that it allows me to write code specifically optimised for JS, and don't have to worry about stuff like thread-safety.

No need to enumerate *all* reasons against this because the motivation here is convenience rather than something more serious, but I think we should keep things as they are. Are you ok with that?

**Comment by cquiroz** [comment]
Yeah I understand the worry and the extra complications of a cross built module
